name: jaffle_shop_classic
description: ''
version: '1.0'
author: vlaunir@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/demo_job:
    name: demo_job
    description: ''
    fabricUID: 9863
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-10-11 16:19:09'
    author: vlaunir@prophecy.io
    models:
    - 34342/.prophecy/metadata/sqlmodels/products
    - 34342/.prophecy/metadata/sqlmodels/stg_supplies
    sqlProjects:
    - '34482'
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-10-11 04:23:52'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/stg_orders:
    name: stg_orders
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: order_id
        dataType:
          type: Bigint
      - name: customer_id
        dataType:
          type: Bigint
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: vlaunir@prophecy.io
    files:
    - models/staging/stg_orders.sql
    - .prophecy/ide/models/stg_orders.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-10-11 04:23:55'
  .prophecy/metadata/sqlmodels/orders:
    name: orders
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: order_id
        dataType:
          type: Bigint
      - name: customer_id
        dataType:
          type: Bigint
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
      - name: credit_card_amount
        dataType:
          type: Float
      - name: coupon_amount
        dataType:
          type: Float
      - name: bank_transfer_amount
        dataType:
          type: Float
      - name: gift_card_amount
        dataType:
          type: Float
      - name: amount
        dataType:
          type: Float
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    author: vlaunir@prophecy.io
    files:
    - models/orders.sql
    - .prophecy/ide/models/orders.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-10-11 04:23:55'
  .prophecy/metadata/sqlmodels/customers:
    name: customers
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: customer_id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
      - name: first_order
        dataType:
          type: Date
      - name: most_recent_order
        dataType:
          type: Date
      - name: number_of_orders
        dataType:
          type: Bigint
      - name: customer_lifetime_value
        dataType:
          type: Float
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    author: vlaunir@prophecy.io
    files:
    - models/customers.sql
    - .prophecy/ide/models/customers.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-10-11 04:23:55'
  .prophecy/metadata/sqlmodels/stg_payments:
    name: stg_payments
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: payment_id
        dataType:
          type: Bigint
      - name: order_id
        dataType:
          type: Bigint
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Float
    description: null
    author: vlaunir@prophecy.io
    files:
    - models/staging/stg_payments.sql
    - .prophecy/ide/models/stg_payments.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-10-11 04:23:55'
  .prophecy/metadata/sqlmodels/stg_customers:
    name: stg_customers
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: customer_id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: vlaunir@prophecy.io
    files:
    - models/staging/stg_customers.sql
    - .prophecy/ide/models/stg_customers.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-10-11 04:23:55'
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/raw_customers:
    name: raw_customers
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: vlaunir@prophecy.io
    files:
    - seeds/raw_customers.csv
    createdAt: '2024-10-11 04:23:55'
  .prophecy/metadata/sqlseeds/raw_orders:
    name: raw_orders
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: user_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: vlaunir@prophecy.io
    files:
    - seeds/raw_orders.csv
    createdAt: '2024-10-11 04:23:55'
  .prophecy/metadata/sqlseeds/raw_payments:
    name: raw_payments
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: order_id
        dataType:
          type: Integer
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Integer
    description: null
    author: vlaunir@prophecy.io
    files:
    - seeds/raw_payments.csv
    createdAt: '2024-10-11 04:23:55'
sqlSources:
  .prophecy/metadata/sqlsources/vlaunir_demos_default:
    name: vlaunir_demos.default
    description: null
    author: vlaunir@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-10-11 16:02:41'
    tables:
    - name: raw_payments
      schema:
        entityType: ''
        providerType: databricks
        fields:
        - name: id
          dataType:
            type: Bigint
        - name: order_id
          dataType:
            type: Bigint
        - name: payment_method
          dataType:
            type: String
        - name: amount
          dataType:
            type: Bigint
      description: Records of payment transactions linked to orders, providing insights
        into payment methods and transaction amounts.
      author: vlaunir@prophecy.io
      createdAt: '2024-10-11 16:02:41'
    - name: raw_orders
      schema:
        entityType: ''
        providerType: databricks
        fields:
        - name: id
          dataType:
            type: Bigint
        - name: user_id
          dataType:
            type: Bigint
        - name: order_date
          dataType:
            type: Date
        - name: status
          dataType:
            type: String
      description: Order records capturing user transactions and statuses, enabling
        insights into purchasing behavior and trends.
      author: vlaunir@prophecy.io
      createdAt: '2024-10-11 16:03:31'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: vlaunir@prophecy.io
  createdAt: '2024-10-11 04:23:52'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
